# build.yml

name: turbo-spoon
#description: 'Builds and publishes the container image to ghcr.io'
on:
  schedule:
    - cron: '20 20 * * *'  # 20:20 everyday
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
env:
  IMAGE_NAME: turbo-spoon
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
jobs:
  push-ghcr:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Push to Registry action
        uses: actions/checkout@v3
      - name: Build Image
        run: podman build -f Containerfile -t turbo-spoon
      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@v2
        env:
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ github.token }}
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ steps.registry_case.outputs.lowercase }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust
