# build.yml

name: turbo-spoon
#description: 'Builds and publishes the container image to ghcr.io'
on:
  schedule:
    - cron: '20 20 * * *'  # 20:20 everyday
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
env:
  IMAGE_NAME: turbo-spoon
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  
jobs:
  push-ghcr:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Push to Registry action
        uses: actions/checkout@v3
        
      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            ./Containerfile
          image: ${{ env.IMAGE_NAME }}
          tags: |
            ${{ steps.generate-tags.outputs.alias_tags }}
            ${{ steps.generate-tags.outputs.date }}
            ${{ steps.generate-tags.outputs.sha_short }}
          build-args: |
            FEDORA_MAJOR_VERSION=${{ matrix.major_version }}
          oci: true
        
      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@v2
        env:
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ github.token }}
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ steps.registry_case.outputs.lowercase }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust
